from pathlib import Path
import json

topics = [
  ("patio-sinking","How to Fix a Sinking Patio in Hamilton, Burlington, and Oakville","Patio sinking after winter? Learn causes, repair options, and local Ontario solutions for homeowners.","Sinking Patio Repair Solutions for Ontario Homes","/assets/images/i1.jpg",["/assets/images/i2.jpg","/assets/images/i11.jpg","/assets/images/i15.jpg"]),
  ("backyard-drainage","Backyard Drainage Problems in Burlington and Hamilton: What Works","Backyard drainage problems in Burlington, Hamilton, and Oakville? Learn practical grading and drainage solutions.","Backyard Drainage Solutions for Standing Water and Soft Lawns","/assets/images/s2.jpg",["/assets/images/s4.jpg","/assets/images/s8.jpg","/assets/images/p5.jpg"]),
  ("retaining-wall-repair","Retaining Wall Leaning Repair in Oakville, Hamilton, and Burlington","Leaning retaining wall in Oakville, Hamilton, or Burlington? Learn repair vs replacement options.","Leaning Retaining Wall Repair and Replacement Guide","/assets/images/i3.jpg",["/assets/images/i4.jpg","/assets/images/i6.jpg","/assets/images/i5.jpg"]),
  ("water-pooling-yard","Water Pooling in Yard? Practical Fixes for Ontario Homeowners","Water pooling in your yard after rain? Learn grading, drainage, and restoration strategies.","How to Fix Water Pooling in Your Yard","/assets/images/s5.jpg",["/assets/images/s6.jpg","/assets/images/s7.jpg","/assets/images/sod1.jpg"]),
  ("uneven-interlock","Uneven Interlock Pavers: Repair Options That Last in Ontario","Uneven interlock pavers in Hamilton, Burlington, or Oakville? Learn why pavers shift and how to fix it.","Uneven Interlock Repair for Driveways, Patios, and Walkways","/assets/images/i10.jpg",["/assets/images/i12.jpg","/assets/images/i13.jpg","/assets/images/i14.jpg"]),
  ("lawn-drainage-problems","Lawn Drainage Problems in Hamilton and Burlington: What to Do","Lawn drainage problems causing soggy grass or moss? Learn causes and repair methods.","Lawn Drainage Problem Fixes for Wet, Soft, or Failing Turf","/assets/images/sod1.jpg",["/assets/images/s3.jpg","/assets/images/s6.jpg","/assets/images/s7.jpg"]),
  ("flooding-backyard","Flooding Backyard Solutions in Hamilton, Dundas, and Oakville","Backyard flooding after storms? Learn practical flood-mitigation solutions for Ontario homes.","Backyard Flooding Repair for Heavy Rain and Spring Melt","/assets/images/p2.jpg",["/assets/images/p6.jpg","/assets/images/s4.jpg","/assets/images/s5.jpg"]),
  ("interlock-repair","Interlock Repair in Hamilton and Burlington: When to Repair vs Replace","Need interlock repair in Hamilton, Burlington, or Oakville? Learn when lift-and-relay works.","Interlock Repair Guide for Patios, Driveways, and Walkways","/assets/images/i18.jpg",["/assets/images/i16.jpg","/assets/images/i17.jpg","/assets/images/i6.jpg"]),
  ("sod-turning-yellow","Sod Turning Yellow? Causes and Fixes for Ontario Lawns","Sod turning yellow in Hamilton, Burlington, or Oakville? Learn drainage and soil recovery steps.","Why New Sod Turns Yellow and How to Fix It","/assets/images/sod1.jpg",["/assets/images/s2.jpg","/assets/images/s4.jpg","/assets/images/s8.jpg"]),
  ("yard-grading-drainage","Yard Grading and Drainage Solutions for Ontario Homes","Need yard grading and drainage in Hamilton, Burlington, or Oakville? Learn process and benefits.","Yard Grading and Drainage: Long-Term Water Management","/assets/images/s6.jpg",["/assets/images/s7.jpg","/assets/images/s8.jpg","/assets/images/c4.jpeg"]),
]

services = [('/services/interlock-patios/','Interlock patios'),('/services/retaining-walls/','Retaining walls'),('/services/sod-installation/','Sod installation'),('/services/yard-grading/','Yard grading and drainage'),('/services/concrete/','Concrete services'),('/services/backyard-landscaping/','Backyard renovations')]
cities = [('/service-areas/hamilton/','Hamilton'),('/service-areas/burlington/','Burlington'),('/service-areas/oakville/','Oakville'),('/service-areas/ancaster/','Ancaster'),('/service-areas/dundas/','Dundas'),('/service-areas/waterdown/','Waterdown'),('/service-areas/stoney-creek/','Stoney Creek'),('/service-areas/milton/','Milton')]

base = Path('solutions'); base.mkdir(exist_ok=True)

def faq(topic):
    qs = [
      f'Why does {topic.replace("-"," ")} get worse after winter in Ontario?',
      'How do you fix uneven interlock pavers or settled surfaces?',
      'Can poor drainage cause patio, lawn, or retaining wall damage?',
      'How much does this type of repair cost in Ontario?',
      'Do I need to replace the entire area?',
      'Do you provide this service in nearby cities too?'
    ]
    ans = [
      'Winter moisture enters weak base layers, then freeze-thaw expansion and spring thaw collapse expose hidden settlement. If base depth is shallow or runoff is concentrated, movement repeats each season. Lasting repair requires structural correction plus drainage control, not a cosmetic top-up.',
      'We lift affected materials, inspect bedding and base, re-excavate failed zones, compact corrected aggregate in controlled lifts, and reinstall to proper line and grade. Then we compact and joint-stabilize the surface. This process addresses root causes instead of temporary visual patching.',
      'Yes. Persistent moisture can wash support fines, soften subgrade, and accelerate movement around patios, walkways, lawns, and retaining features. Poor drainage also increases winter damage risk because freeze-thaw cycles amplify weakness in wet areas. Water management is critical for long-term durability.',
      'Cost depends on affected area, failure depth, access constraints, and whether grading, drainage, or restoration work is needed. Localized corrections cost less than full reconstruction. We provide written scope-based options so homeowners can compare short-term repairs and long-term solutions clearly.',
      'Not always. If materials are in good condition and failure is localized, targeted lift-and-rebuild is often effective. If the issue is widespread or tied to systemic base and drainage problems, broader reconstruction typically delivers better durability and lower lifecycle cost than repeated spot repairs.',
      'Yes. We provide problem-and-solution services across Hamilton, Burlington, Oakville, Ancaster, Dundas, Waterdown, Stoney Creek, and Milton. Each plan is adapted to local slope conditions, clay-soil behavior, and Ontario freeze-thaw performance requirements.'
    ]
    return list(zip(qs,ans))

for slug,title,meta,h1,hero,imgs in topics:
    faqs = faq(slug)
    faq_schema = {'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs]}
    gallery = ''.join([f'<div class="service-gallery-item"><img src="{im}" alt="{slug}-project-photo" loading="lazy" /></div>' for im in imgs])
    svc = ''.join([f'<li><a href="{u}">{t}</a></li>' for u,t in services])
    cty = ''.join([f'<li><a href="{u}">{t}</a></li>' for u,t in cities])
    faq_html = ''.join([f'<div class="faq-item"><button type="button" class="faq-question" aria-expanded="false">{q}</button><div class="faq-answer"><div class="faq-answer-inner">{a}</div></div></div>' for q,a in faqs])

    intro = f"Homeowners in Hamilton, Burlington, Oakville, Ancaster, Dundas, Waterdown, Stoney Creek, and Milton search for {slug.replace('-', ' ')} solutions when recurring property issues keep returning after rain or winter thaw. This page explains what causes the problem, how to solve it correctly, and how Seven Stones Landscape builds durable repairs for Ontario conditions."
    causes = f"Most failures begin with shallow base prep, weak compaction, or poor runoff planning. Ontario freeze-thaw cycles and clay-heavy soil magnify these weaknesses, especially when water repeatedly collects in one zone. Properties in Hamilton and Burlington often show movement first near transitions between lawn and hardscape. In Oakville and nearby areas, concentrated roof runoff can quietly overload patio corners or soft lawn areas until visible damage appears."
    fix = f"Our process starts with a full-site diagnostic so we can map where water enters, where it concentrates, and where structural support is failing. Then we rebuild failed layers at the right depth, restore grade, and integrate the solution with surrounding surfaces. Where required, we coordinate {services[0][1].lower()}, {services[3][1].lower()}, and {services[5][1].lower()} so the repaired area remains stable instead of failing again next season."
    local = "Local conditions matter. Hamilton homeowners often experience movement from freeze-thaw stress on variable slopes, while Burlington and Oakville lots frequently need clay-aware drainage strategy. Ancaster, Dundas, Waterdown, and Stoney Creek properties can also show seasonal elevation shifts, which is why compaction quality, controlled runoff, and proper transitions are essential."
    case = f"Typical case: a homeowner reported persistent {slug.replace('-', ' ')} symptoms after storms and spring thaw. We identified the structural cause, corrected grading and support layers, and restored the finish surface. After the repair, water cleared properly, movement stopped, and the area stayed functional through the next weather cycle."

    html = f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{title} | Seven Stones Landscape</title><meta name="description" content="{meta}" /><meta name="robots" content="index, follow" />
<link rel="canonical" href="https://sevenstoneslandscape.ca/solutions/{slug}/" />
<link rel="icon" href="/favicon.ico" sizes="any" /><link rel="icon" href="/assets/images/icon.png" type="image/png" /><link rel="shortcut icon" href="/favicon.ico" /><link rel="apple-touch-icon" href="/assets/images/icon.png" />
<meta property="og:type" content="website" /><meta property="og:title" content="{title} | Seven Stones Landscape" /><meta property="og:description" content="{meta}" /><meta property="og:url" content="https://sevenstoneslandscape.ca/solutions/{slug}/" /><meta property="og:image" content="https://sevenstoneslandscape.ca{hero}" /><meta property="og:locale" content="en_CA" /><meta name="twitter:card" content="summary_large_image" />
<link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="/css/styles.css" /><link rel="stylesheet" href="/css/service-page.css" />
<script type="application/ld+json">{json.dumps(faq_schema,separators=(',',':'))}</script>
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"Home","item":"https://sevenstoneslandscape.ca/"}},{{"@type":"ListItem","position":2,"name":"Solutions","item":"https://sevenstoneslandscape.ca/solutions/"}},{{"@type":"ListItem","position":3,"name":"{slug}","item":"https://sevenstoneslandscape.ca/solutions/{slug}/"}}]}}</script></head>
<body class="service-page" data-phone="+1 (289) 700-0312" data-email="john.scime.mcmaster@gmail.com"><div id="header-placeholder"></div>
<main id="service-main" class="main-with-hero"><section class="service-hero" aria-labelledby="solution-heading"><div class="service-hero-bg" role="img" aria-label="{h1}"></div><div class="service-hero-overlay"></div><div class="container"><div class="service-hero-content"><p class="service-hero-label">Solutions Hub</p><h1 id="solution-heading" class="service-hero-title">{h1}</h1><p class="service-hero-intro">{intro} <a href="/contact/">Request a free quote</a>.</p><div class="service-hero-actions"><a href="/contact/" class="btn btn--service-cta">Get a Free Quote</a><a href="tel:+1 (289) 700-0312" class="btn btn--service-outline">+1 (289) 700-0312</a></div></div></div></section>
<section class="section service-gallery" aria-labelledby="gallery-heading"><div class="container"><h2 id="gallery-heading" class="service-gallery-title">Related Project Photos</h2><div class="service-gallery-grid">{gallery}</div></div></section>
<section class="section section--cream service-content"><div class="container"><div class="content-blocks"><h2 class="content-block-title">Problem Introduction</h2><div class="service-h1-underline" aria-hidden="true"></div><p>{intro}</p><h2 class="content-block-title">Why This Problem Happens</h2><div class="service-h1-underline" aria-hidden="true"></div><p>{causes}</p><h2 class="content-block-title">How Seven Stones Landscape Fixes It</h2><div class="service-h1-underline" aria-hidden="true"></div><p>{fix}</p><h2 class="content-block-title">Local Considerations</h2><div class="service-h1-underline" aria-hidden="true"></div><p>{local}</p><h2 class="content-block-title">Related Services</h2><div class="service-h1-underline" aria-hidden="true"></div><ul class="service-expert-list">{svc}</ul><h2 class="content-block-title">City Pages</h2><div class="service-h1-underline" aria-hidden="true"></div><ul class="service-expert-list">{cty}</ul><h2 class="content-block-title">Before &amp; After Case Example</h2><div class="service-h1-underline" aria-hidden="true"></div><p>{case}</p><h2 class="content-block-title">Action Plan for Homeowners</h2><div class="service-h1-underline" aria-hidden="true"></div><p>Document when and where symptoms appear, especially after storms and spring thaw. Avoid repeated short-term patching until root causes are confirmed. A structured inspection and written scope helps prioritize high-impact corrections before cosmetic upgrades.</p><p>We build solution-first plans that align structural correction, drainage, and finish restoration. This prevents duplicated spending and improves long-term performance. If needed, projects can be phased by urgency and budget while preserving technical integrity.</p><p>Every lot behaves differently based on slope, subgrade, and existing hardscape. That is why two homes on the same street can require different methods. We design for site-specific behavior so repairs remain reliable through Ontario weather cycles.</p><p>When repairs are complete, we review adjacent surfaces and transitions to reduce new stress points. This integrated approach protects patios, driveways, lawns, and retaining features together instead of solving one issue while creating another.</p></div></div></section>
<section class="section faq-section" aria-labelledby="faq-heading"><div class="container"><h2 id="faq-heading" class="section-title">Frequently Asked Questions</h2><div class="service-h1-underline" style="margin-left:0;" aria-hidden="true"></div><div class="faq-inner" style="margin-top:var(--space-lg);"><div class="faq-list" style="max-width:100%;">{faq_html}</div></div></div></section>
<section class="section cta-bottom-bg" aria-label="Get a quote"><div class="container"><div class="cta-band-inner"><h2 class="section-title section-title--light">Need Help With This Problem?</h2><p class="section-intro section-intro--light">We provide practical local solutions across Hamilton, Burlington, Oakville, Ancaster, Dundas, Waterdown, Stoney Creek, and Milton.</p><div class="cta-band-actions"><a href="/contact/" class="btn btn--cta">Get a Free Quote</a><a href="tel:+1 (289) 700-0312" class="btn btn--white">+1 (289) 700-0312</a></div></div></div></section></main>
<div id="footer-placeholder"></div><script src="/js/main.js" defer></script></body></html>'''

    d = Path('solutions') / slug
    d.mkdir(exist_ok=True)
    (d / 'index.html').write_text(html, encoding='utf-8')
    (Path('solutions') / f'{slug}.html').write_text(f'<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Redirecting | Seven Stones Landscape</title><meta name="robots" content="noindex, follow" /><link rel="canonical" href="https://sevenstoneslandscape.ca/solutions/{slug}/" /><meta http-equiv="refresh" content="0; url=/solutions/{slug}/" /><script>window.location.replace(\'/solutions/{slug}/\');</script></head><body><p>Redirecting. <a href="/solutions/{slug}/">Continue</a>.</p></body></html>', encoding='utf-8')

cards = ''.join([f"<article class='service-card reveal'><div class='service-body'><span class='service-tag'>Problem &amp; Solution</span><h3><a href='/solutions/{slug}/'>{title}</a></h3><p>{meta}</p></div></article>" for slug,title,meta,*_ in topics])
index_html = f'''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Landscaping Problem &amp; Solution Hub | Seven Stones Landscape</title><meta name="description" content="Explore local landscaping problem and solution guides for Hamilton, Burlington, Oakville, Ancaster, Dundas, Waterdown, Stoney Creek, and Milton homeowners." /><meta name="robots" content="index, follow" /><link rel="canonical" href="https://sevenstoneslandscape.ca/solutions/" /><link rel="icon" href="/favicon.ico" sizes="any" /><link rel="icon" href="/assets/images/icon.png" type="image/png" /><link rel="shortcut icon" href="/favicon.ico" /><link rel="apple-touch-icon" href="/assets/images/icon.png" /><meta property="og:type" content="website" /><meta property="og:title" content="Landscaping Problem &amp; Solution Hub | Seven Stones Landscape" /><meta property="og:description" content="Long-tail local solution pages for drainage, interlock, retaining walls, sod, and concrete issues across Ontario service areas." /><meta property="og:url" content="https://sevenstoneslandscape.ca/solutions/" /><meta property="og:image" content="https://sevenstoneslandscape.ca/assets/images/hero.jpg" /><meta property="og:locale" content="en_CA" /><link rel="preconnect" href="https://fonts.googleapis.com" /><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet" /><link rel="stylesheet" href="/css/styles.css" /><script type="application/ld+json">{{"@context":"https://schema.org","@type":"CollectionPage","name":"Solutions Hub","url":"https://sevenstoneslandscape.ca/solutions/","description":"Problem and solution guides for landscaping and hardscaping homeowners in Ontario.","isPartOf":{{"@id":"https://sevenstoneslandscape.ca/#website"}}}}</script></head><body data-phone="+1 (289) 700-0312" data-email="john.scime.mcmaster@gmail.com"><div id="header-placeholder"></div><main><section class="section section--cream"><div class="container"><p class="section-label">Problem &amp; Solution SEO Hub</p><h1 class="section-title">Landscaping Problem &amp; Solution Guides</h1><p class="section-intro">These pages target real homeowner searches like "how to fix a sinking patio Hamilton" and "backyard drainage problems Burlington," with practical, local solutions and direct service links.</p><div class="services-grid">{cards}</div></div></section></main><div id="footer-placeholder"></div><script src="/js/main.js" defer></script></body></html>'''
Path('solutions/index.html').write_text(index_html, encoding='utf-8')
Path('solutions.html').write_text('<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Redirecting | Seven Stones Landscape</title><meta name="robots" content="noindex, follow" /><link rel="canonical" href="https://sevenstoneslandscape.ca/solutions/" /><meta http-equiv="refresh" content="0; url=/solutions/" /><script>window.location.replace(\'/solutions/\');</script></head><body><p>Redirecting. <a href="/solutions/">Continue</a>.</p></body></html>', encoding='utf-8')
print('generated', len(topics))
